import { createContext, useContext, useState } from "react";

const translations = {
  en: {
    nav: {
      services: "SERVICES",
      process: "PROCESS",
      about: "ABOUT",
      testimonials: "TESTIMONIALS",
      contact: "CONTACT",
      getQuote: "Get a Quote",
    },
    hero: {
      status: "Active Transfers — Montréal Region",
      headline1: "We Move",
      headline2: "The Space",
      headline3: "Around You",
      subtitle: "Kostas Déménagement — Montreal's premier moving company. Precision logistics for residential and commercial relocations.",
      ctaPrimary: "Launch Logistics",
      ctaSecondary: "Explore Services",
      stat1: "Relocations",
      stat2: "Years Active",
      stat3: "Insured Value",
      scroll: "Scroll",
    },
    services: {
      phase: "Phase_01: Service Manifest",
      heading1: "What We",
      heading2: "Move",
      imgLabel1: "Precision Equipment",
      imgLabel2: "Spatial Assessment",
      imgLabel3: "Expert Handling",
      s1title: "Residential Moving",
      s1desc: "Full-service home relocation with meticulous care for every personal item. From studios to estates.",
      s2title: "Commercial Moving",
      s2desc: "Minimal downtime office and business relocations. Coordinated logistics for seamless transitions.",
      s3title: "Packing & Crating",
      s3desc: "Professional packing with premium materials. Custom crating for high-value and fragile items.",
      s4title: "Long Distance",
      s4desc: "Cross-province and interprovincial relocations with GPS tracking and guaranteed delivery windows.",
      s5title: "Secure Storage",
      s5desc: "Climate-controlled facilities with 24/7 surveillance. Short and long-term options available.",
      s6title: "Last Minute Moves",
      s6desc: "Emergency relocation services with rapid deployment. Available 7 days a week, year round.",
    },
    process: {
      phase: "Phase_02: Operations Protocol",
      heading1: "How We",
      heading2: "Operate",
      step1title: "Consultation",
      step1sub: "Assessment & Planning",
      step1desc: "We conduct a thorough assessment of your inventory, map optimal routes, and build a custom logistics plan tailored to your timeline.",
      step2title: "Preparation",
      step2sub: "Packing & Securing",
      step2desc: "Our certified team uses premium-grade materials to protect every item. Fragile and high-value pieces receive custom crating.",
      step3title: "Transport",
      step3sub: "Relocation in Motion",
      step3desc: "GPS-tracked fleet ensures real-time visibility. Climate-controlled vehicles for sensitive items. On-time guaranteed delivery.",
      step4title: "Delivery",
      step4sub: "Final Placement",
      step4desc: "Strategic unloading and placement per your floor plan. Furniture assembly, debris removal, and a final walkthrough with you.",
    },
    about: {
      phase: "Phase_03: Company Intel",
      heading1: "Moving With",
      heading2: "Precision",
      p1: "Founded by Kostas with a single truck and an obsession for perfection, Kostas Déménagement has grown into Montreal's most trusted moving operation. We treat every relocation as a precision logistics mission — not just moving boxes, but orchestrating seamless spatial transitions.",
      p2: "Our team of 50+ certified professionals operates a modern fleet equipped with GPS tracking, air-ride suspension, and climate control. Every move is fully insured and backed by our satisfaction guarantee.",
      stat1: "Years of Excellence",
      stat2: "Expert Team Members",
      stat3: "Successful Moves",
      stat4: "Customer Rating",
      badge: "Years Active",
    },
    testimonials: {
      phase: "Phase_04: Client Reports",
      heading1: "Verified",
      heading2: "Testimonials",
      t1name: "Marie-Claire Dubois",
      t1loc: "Plateau to Westmount",
      t1text: "Absolutely impeccable. They handled our grand piano and art collection like museum curators. Not a scratch, not a worry. Truly world-class.",
      t1type: "Residential",
      t2name: "Jean-François Tremblay",
      t2loc: "Downtown Office Relocation",
      t2text: "We moved our 80-person office over a weekend with zero downtime. Monday morning, everything was set up and running. Incredible coordination.",
      t2type: "Commercial",
      t3name: "Sophie Chen",
      t3loc: "NDG to Laval",
      t3text: "Third time using Kostas. They remember our preferences, handle everything with care, and always arrive on time. The only movers I'll ever use.",
      t3type: "Residential",
    },
    contact: {
      phase: "Phase_05: Initiate Transfer",
      heading1: "Request",
      heading2: "Quote",
      subtitle: "Every move begins with a conversation. Tell us about your relocation needs and we'll craft a precise logistics plan with transparent pricing.",
      addr: "Headquarters",
      addrVal: "Montréal, QC, Canada",
      phone: "Operations Line",
      phoneVal: "514-885-0785",
      email: "Digital Comms",
      emailVal: "kostasdemenagement@gmail.com",
      website: "Website",
      websiteVal: "https://kostasmoving.ca",
      hours: "Operating Hours",
      hoursVal: "Mon–Sun 9:00 AM–9:00 PM",
      formStatus: "Quote Form — Active",
      labelName: "Full Name *",
      labelEmail: "Email *",
      labelPhone: "Phone",
      labelType: "Move Type *",
      labelDate: "Preferred Date",
      labelDetails: "Additional Details",
      placeName: "Your name",
      placeEmail: "email@example.com",
      placePhone: "514-885-0785",
      placeType: "Select type",
      placeDetails: "Tell us about your move — origins, destination, special items...",
      typeRes: "Residential",
      typeCom: "Commercial",
      typeLong: "Long Distance",
      typeStore: "Storage Only",
      submit: "Submit Request",
      disclaimer: "Free estimate • No obligation • Response within 2 hours",
      successTitle: "Quote Requested",
      successText: "Your logistics plan is being prepared. Our team will contact you within 2 business hours with a detailed proposal.",
      successStatus: "Status: Processing",
    },
    footer: {
      tagline: "Montreal's premier moving company. Precision logistics for every spatial transition for over 8 years.",
      manifestLabel: "Shipping Manifest — Contact Registry",
      addr: "",
      phone: "514-885-0785",
      email: "kostasdemenagement@gmail.com",
      websiteVal: "kostasmoving.ca",
      services: "Services",
      process: "Process",
      about: "About",
      testimonials: "Testimonials",
      rights: "ALL RIGHTS RESERVED",
      permit: "PERMIT: QC-MOV-2024-1234 • INSURED & BONDED",
    },
  },

  fr: {
    nav: {
      services: "SERVICES",
      process: "PROCESSUS",
      about: "À PROPOS",
      testimonials: "TÉMOIGNAGES",
      contact: "CONTACT",
      getQuote: "Obtenir un devis",
    },
    hero: {
      status: "Transferts actifs — Région de Montréal",
      headline1: "Nous déplaçons",
      headline2: "L'espace",
      headline3: "Autour de vous",
      subtitle: "Kostas Déménagement — l'entreprise de déménagement de premier plan à Montréal. Logistique de précision pour les déménagements résidentiels et commerciaux.",
      ctaPrimary: "Lancer la logistique",
      ctaSecondary: "Explorer les services",
      stat1: "Déménagements",
      stat2: "Années d'activité",
      stat3: "Valeur assurée",
      scroll: "Défiler",
    },
    services: {
      phase: "Phase_01: Manifeste des services",
      heading1: "Ce que nous",
      heading2: "Déplaçons",
      imgLabel1: "Équipement de précision",
      imgLabel2: "Évaluation spatiale",
      imgLabel3: "Manipulation experte",
      s1title: "Déménagement résidentiel",
      s1desc: "Service complet de déménagement à domicile avec un soin méticuleux pour chaque article. Des studios aux grandes propriétés.",
      s2title: "Déménagement commercial",
      s2desc: "Déménagements de bureaux et d'entreprises avec un temps d'arrêt minimal. Logistique coordonnée pour des transitions sans faille.",
      s3title: "Emballage & mise en caisse",
      s3desc: "Emballage professionnel avec des matériaux de première qualité. Mise en caisse sur mesure pour les articles de grande valeur et fragiles.",
      s4title: "Longue distance",
      s4desc: "Déménagements interprovinciaux avec suivi GPS et fenêtres de livraison garanties.",
      s5title: "Entreposage sécurisé",
      s5desc: "Installations climatisées sous surveillance 24h/24. Options à court et à long terme disponibles.",
      s6title: "Déménagements de dernière minute",
      s6desc: "Services de déménagement d'urgence à déploiement rapide. Disponible 7 jours sur 7, toute l'année.",
    },
    process: {
      phase: "Phase_02: Protocole d'opérations",
      heading1: "Comment nous",
      heading2: "Opérons",
      step1title: "Consultation",
      step1sub: "Évaluation & planification",
      step1desc: "Nous effectuons une évaluation approfondie de votre inventaire, traçons les itinéraires optimaux et élaborons un plan logistique personnalisé selon votre calendrier.",
      step2title: "Préparation",
      step2sub: "Emballage & sécurisation",
      step2desc: "Notre équipe certifiée utilise des matériaux de qualité supérieure pour protéger chaque article. Les pièces fragiles et de grande valeur bénéficient d'une mise en caisse personnalisée.",
      step3title: "Transport",
      step3sub: "Déménagement en cours",
      step3desc: "Notre flotte suivie par GPS assure une visibilité en temps réel. Véhicules climatisés pour les articles sensibles. Livraison garantie dans les délais.",
      step4title: "Livraison",
      step4sub: "Placement final",
      step4desc: "Déchargement stratégique et placement selon votre plan d'étage. Montage des meubles, enlèvement des débris et visite finale avec vous.",
    },
    about: {
      phase: "Phase_03: Renseignements société",
      heading1: "Déménager avec",
      heading2: "Précision",
      p1: "Fondé par Kostas avec un seul camion et une obsession de la perfection, Kostas Déménagement est devenu l'entreprise de déménagement la plus fiable de Montréal. Nous traitons chaque déménagement comme une mission logistique de précision — pas seulement déplacer des boîtes, mais orchestrer des transitions spatiales fluides.",
      p2: "Notre équipe de plus de 50 professionnels certifiés exploite une flotte moderne équipée du suivi GPS, de la suspension pneumatique et du contrôle climatique. Chaque déménagement est entièrement assuré et garanti par notre promesse de satisfaction.",
      stat1: "Années d'excellence",
      stat2: "Membres d'équipe experts",
      stat3: "Déménagements réussis",
      stat4: "Note clients",
      badge: "Années d'activité",
    },
    testimonials: {
      phase: "Phase_04: Rapports clients",
      heading1: "Témoignages",
      heading2: "Vérifiés",
      t1name: "Marie-Claire Dubois",
      t1loc: "Plateau-Mont-Royal à Westmount",
      t1text: "Absolument impeccable. Ils ont manipulé notre piano à queue et notre collection d'art comme des conservateurs de musée. Pas une égratignure, aucune inquiétude. Vraiment exceptionnel.",
      t1type: "Résidentiel",
      t2name: "Jean-François Tremblay",
      t2loc: "Déménagement de bureau au centre-ville",
      t2text: "Nous avons déménagé notre bureau de 80 personnes en un week-end sans aucun temps d'arrêt. Le lundi matin, tout était installé et fonctionnel. Une coordination incroyable.",
      t2type: "Commercial",
      t3name: "Sophie Chen",
      t3loc: "NDG à Laval",
      t3text: "Troisième fois avec Kostas. Ils se souviennent de nos préférences, gèrent tout avec soin et arrivent toujours à l'heure. Les seuls déménageurs que j'utiliserai jamais.",
      t3type: "Résidentiel",
    },
    contact: {
      phase: "Phase_05: Initier le transfert",
      heading1: "Demander",
      heading2: "Un devis",
      subtitle: "Tout déménagement commence par une conversation. Parlez-nous de vos besoins et nous élaborerons un plan logistique précis avec une tarification transparente.",
      addr: "Siège social",
      addrVal: "Montréal, QC, Canada",
      phone: "Ligne opérationnelle",
      phoneVal: "514-885-0785",
      email: "Communications",
      emailVal: "kostasdemenagement@gmail.com",
      website: "Site web",
      websiteVal: "https://kostasmoving.ca",
      hours: "Heures d'ouverture",
      hoursVal: "Lun–Dim 9h00–21h00",
      formStatus: "Formulaire de devis — Actif",
      labelName: "Nom complet *",
      labelEmail: "Courriel *",
      labelPhone: "Téléphone",
      labelType: "Type de déménagement *",
      labelDate: "Date souhaitée",
      labelDetails: "Détails supplémentaires",
      placeName: "Votre nom",
      placeEmail: "courriel@exemple.com",
      placePhone: "514-885-0785",
      placeType: "Sélectionner le type",
      placeDetails: "Parlez-nous de votre déménagement — origine, destination, articles spéciaux...",
      typeRes: "Résidentiel",
      typeCom: "Commercial",
      typeLong: "Longue distance",
      typeStore: "Entreposage seulement",
      submit: "Soumettre la demande",
      disclaimer: "Estimation gratuite • Sans obligation • Réponse en 2 heures",
      successTitle: "Devis demandé",
      successText: "Votre plan logistique est en cours de préparation. Notre équipe vous contactera dans les 2 heures ouvrables avec une proposition détaillée.",
      successStatus: "Statut : En traitement",
    },
    footer: {
      tagline: "L'entreprise de déménagement de premier plan à Montréal. Logistique de précision pour chaque transition spatiale depuis plus de 8 ans.",
      manifestLabel: "Manifeste d'expédition — Registre des contacts",
      addr: "",
      phone: "514-885-0785",
      email: "kostasdemenagement@gmail.com",
      websiteVal: "kostasmoving.ca",
      services: "Services",
      process: "Processus",
      about: "À propos",
      testimonials: "Témoignages",
      rights: "TOUS DROITS RÉSERVÉS",
      permit: "PERMIS : QC-MOV-2024-1234 • ASSURÉ & CAUTIONNÉ",
    },
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState("fr");
  const t = translations[lang];
  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}