export const adminT = {
  en: {
    panel: "Admin Panel",
    subtitle: "Kostas Déménagement — Requests",
    search: "Search by name, email, phone...",
    refresh: "Refresh",
    backToSite: "← Back to site",
    empty: "Empty",
    columns: {
      new: "New",
      confirmed: "Confirmed",
      in_progress: "In Progress",
      completed: "Completed",
      cancelled: "Cancelled",
    },
    stats: {
      total: "Total Requests",
      confirmed: "Confirmed",
      inProgress: "In Progress",
      completed: "Completed",
      revenue: "Revenue",
    },
    modal: {
      request: "Request",
      status: "Request Status",
      clientData: "Client Info",
      phone: "Phone",
      email: "Email",
      moveDate: "Move Date",
      moveType: "Move Type",
      details: "Details",
      checklist: "Checklist",
      done: "done",
      checklistItems: {
        quote_sent: "Quote sent to client",
        deposit_received: "Deposit received",
        crew_assigned: "Crew assigned",
        truck_booked: "Truck booked",
        client_confirmed: "Client confirmed",
      },
      price: "Estimated Price (CAD)",
      notes: "Internal Notes",
      notesPlaceholder: "Notes for internal use...",
      save: "Save",
      delete: "Delete Request",
      confirmDelete: "Confirm Delete",
      cancel: "Cancel",
      statuses: {
        new: "New",
        confirmed: "Confirmed",
        in_progress: "In Progress",
        completed: "Completed",
        cancelled: "Cancelled",
      },
      types: {
        residential: "Residential",
        commercial: "Commercial",
        long_distance: "Long Distance",
        storage: "Storage Only",
      },
    },
    card: {
      checklist: "Checklist",
    },
  },
  fr: {
    panel: "Panneau Admin",
    subtitle: "Kostas Déménagement — Demandes",
    search: "Recherche par nom, email, téléphone...",
    refresh: "Actualiser",
    backToSite: "← Retour au site",
    empty: "Vide",
    columns: {
      new: "Nouvelles",
      confirmed: "Confirmées",
      in_progress: "En cours",
      completed: "Terminées",
      cancelled: "Annulées",
    },
    stats: {
      total: "Total demandes",
      confirmed: "Confirmées",
      inProgress: "En cours",
      completed: "Terminées",
      revenue: "Revenus",
    },
    modal: {
      request: "Demande",
      status: "Statut de la demande",
      clientData: "Infos client",
      phone: "Téléphone",
      email: "Courriel",
      moveDate: "Date de déménagement",
      moveType: "Type de déménagement",
      details: "Détails",
      checklist: "Liste de contrôle",
      done: "fait",
      checklistItems: {
        quote_sent: "Devis envoyé au client",
        deposit_received: "Dépôt reçu",
        crew_assigned: "Équipe assignée",
        truck_booked: "Camion réservé",
        client_confirmed: "Client confirmé",
      },
      price: "Prix estimé (CAD)",
      notes: "Notes internes",
      notesPlaceholder: "Notes pour usage interne...",
      save: "Sauvegarder",
      delete: "Supprimer la demande",
      confirmDelete: "Confirmer la suppression",
      cancel: "Annuler",
      statuses: {
        new: "Nouvelle",
        confirmed: "Confirmée",
        in_progress: "En cours",
        completed: "Terminée",
        cancelled: "Annulée",
      },
      types: {
        residential: "Résidentiel",
        commercial: "Commercial",
        long_distance: "Longue distance",
        storage: "Entreposage seulement",
      },
    },
    card: {
      checklist: "Liste de contrôle",
    },
  },
};